spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
      resolve-hidden: false
logging:
  level:
    root: INFO
    org.springframework.security: INFO
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs
  info:
    title: TODO APIw
    description: TODO API 문서
    version: v1.0.1
server:
  forward-headers-strategy: framework


---
spring :
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zxtodoxz?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: kwonojou1120

---
spring :
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tododb?serverTimezone=UTC
    username: todo
    password: todopw


